console.log(`true && false: ${true && false}`);
console.log(`"1" != 1: ${"1" != 1}`);
console.log(`"1" !== 1: ${"1" !== 1}`);
console.log(`"1" && 1: ${"1" && 1}`);
console.log(`"1" || 1: ${"1" || 1}`);
console.log(`!1: ${!1}`);
console.log(`!true: ${!true}`);
console.log(`!false: ${!false}`);
console.log(`!(1 > 2): ${!(1 > 2)}`);
console.log(`!(1 < 2): ${!(1 < 2)}`); 
console.log(`!(1 >= 2): ${!(1 >= 2)}`);
console.log(`!(1 <= 2): ${!(1 <= 2)}`);
console.log(`!(1 && 2): ${!(1 && 2)}`);
console.log(`!(1 || 2): ${!(1 || 2)}`);
console.log(`!(true && false): ${!(true && false)}`);
console.log(`!(true || false): ${!(true || false)}`);